---
dist: xenial
language: python
python: 3.7
services: docker
install:
- git clone https://github.com/systemslab/popper
- export PYTHONUNBUFFERED=1
- pip install popper/cli
script: popper run --recursive
